import type { Metadata } from "next";
import "./globals.scss";
import LayoutClient from "./layout.c";

export const metadata: Metadata = {
  title: "Sallix ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=localStorage.getItem('theme');if(t==='dark')document.documentElement.setAttribute('data-theme','dark');})()`,
          }}
        />
      </head>
      <body cz-shortcut-listen="true">
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
